### ISSUE TITLE
db_manage script not working

### ISSUE THREAD

**Issue by grzanka** [yaptide/app#527]
After running locally in docker:

```
(venv) grzanka@grzankax1:~/workspace/yaptide$ docker exec -w /usr/local/app/ yaptide_flask python3 yaptide/admin/db_manage.py add-user admin --password mysecretpassword
Adding user: admin
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1223, in __getattr__
    return self._index[key]
KeyError: 'auth_provider'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/app/yaptide/admin/db_manage.py", line 234, in <module>
    run()
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/app/yaptide/admin/db_manage.py", line 103, in add_user
    if user_exists(username, "YaptideUser", users, con):
  File "/usr/local/app/yaptide/admin/db_manage.py", line 39, in user_exists
    query = db.select(users).where(users.c.username == name, users.c.auth_provider == auth_provider)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/base.py", line 1225, in __getattr__
    util.raise_(AttributeError(key), replace_context=err)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
AttributeError: auth_provider
```

**Comment by grzanka** [comment]
Not valid, I had outdated volume for DB storage
